# Generated by Django 6.0.4 on 2026-04-22 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tdp_watts', models.IntegerField(help_text='Consumo de energia em Watts')),
                ('estoque', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MemoriaRAM',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.componente')),
                ('tipo_memoria', models.CharField(max_length=10)),
                ('frequencia_mhz', models.IntegerField()),
            ],
            bases=('hardware.componente',),
        ),
        migrations.CreateModel(
            name='PlacaMae',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.componente')),
                ('socket', models.CharField(help_text='Ex: AM5, LGA1700', max_length=30)),
                ('tipo_memoria', models.CharField(help_text='Ex: DDR4, DDR5', max_length=10)),
            ],
            bases=('hardware.componente',),
        ),
        migrations.CreateModel(
            name='Processador',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.componente')),
                ('socket', models.CharField(max_length=30)),
                ('video_integrado', models.BooleanField(default=False)),
            ],
            bases=('hardware.componente',),
        ),
        migrations.CreateModel(
            name='Montagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_build', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('memoria_ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.memoriaram')),
                ('placa_mae', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.placamae')),
                ('processador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.processador')),
            ],
        ),
    ]
