# Generated by Django 6.0.4 on 2026-05-14 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('potencia_w', models.IntegerField(help_text='Potência em Watts (Ex: 600)')),
                ('certificacao', models.CharField(help_text='Ex: 80 Plus Bronze', max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlacaDeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('memoria_vram', models.CharField(help_text='Ex: 8GB GDDR6', max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tdp', models.IntegerField(help_text='Consumo em Watts (W)')),
            ],
        ),
        migrations.AddField(
            model_name='montagem',
            name='fonte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.fonte'),
        ),
        migrations.AddField(
            model_name='montagem',
            name='placa_de_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.placadevideo'),
        ),
    ]
