# Generated by Django 6.0.4 on 2026-06-25 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_cooler_gabinete_headset_mouse_ssd_teclado_kitpc_ssd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='montagem',
            name='cooler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.cooler'),
        ),
        migrations.AddField(
            model_name='montagem',
            name='gabinete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.gabinete'),
        ),
        migrations.AddField(
            model_name='montagem',
            name='headset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.headset'),
        ),
        migrations.AddField(
            model_name='montagem',
            name='mouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.mouse'),
        ),
        migrations.AddField(
            model_name='montagem',
            name='teclado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.teclado'),
        ),
    ]
